"""Add actions table for tracking game state

Revision ID: database_v4
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""
from alembic import op
import sqlalchemy as sa

from datetime import datetime

# revision identifiers, used by Alembic.
revision = "database_v4"
down_revision = "database_v3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("action_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("result", sa.String(length=100), nullable=True),
        sa.Column("owner", sa.String(length=100), nullable=False, default="NONE"),
        sa.Column("timestamp", sa.DateTime(), nullable=False, default=datetime.utcnow),
        sa.Column("spare", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("action_id"),
    )

    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_foreign_key(
            op.f("fk_actions_game_game_id"),
            "actions",
            ["game_id"],
            ["game_id"],
        )

        batch_op.add_column(
            sa.Column(
                "game_steam_build_branch",
                sa.String(length=256),
                default="public",
                nullable=True,
            ),
        )

        batch_op.add_column(
            sa.Column(
                "game_steam_build_id",
                sa.Integer(),
                default=-1,
                nullable=True,
            ),
        )

        # Set back to nullable and fill with a default value.
        batch_op.alter_column(
            "game_steam_build_branch", nullable=False, server_default="public"
        )

        # Set back to nullable and fill with a default value.
        batch_op.alter_column(
            "game_steam_build_id", nullable=False, server_default="-1"
        )

    op.create_index("ix_actions_action_id", "actions", ["action_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("actions")

    op.drop_constraint("fk_actions_game_game_id", "games", type_="foreignkey")

    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_column("game_steam_build_id")
        batch_op.drop_column("game_steam_build_branch")
    # ### end Alembic commands ###
