"""Initial Migration.

Revision ID: database_v1
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "database_v1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("game_steam_id", sa.Integer(), nullable=False),
        sa.Column("game_install_dir", sa.String(length=256), nullable=False),
        sa.Column("game_name", sa.String(length=256), nullable=False),
        sa.Column("game_pretty_name", sa.String(length=256), nullable=False),
        sa.Column("game_pid", sa.Integer(), nullable=True),
        sa.Column("game_created", sa.DateTime(), nullable=False),
        sa.Column("game_last_update", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("game_id"),
        sa.UniqueConstraint("game_install_dir"),
        sa.UniqueConstraint("game_steam_id"),
    )
    op.create_table(
        "settings",
        sa.Column("setting_id", sa.Integer(), nullable=False),
        sa.Column("setting_name", sa.String(length=256), nullable=False),
        sa.Column("setting_value", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("setting_id"),
        sa.UniqueConstraint("setting_name"),
    )
    op.create_table(
        "game_arguments",
        sa.Column("game_arg_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("game_arg", sa.String(length=256), nullable=False),
        sa.Column("game_arg_value", sa.String(length=256), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("is_permanent", sa.Boolean(), nullable=False),
        sa.Column("file_mode", sa.Integer(), nullable=False),
        sa.Column("use_equals", sa.Boolean(), nullable=False),
        sa.Column("use_quotes", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.game_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_arg_id"),
    )
    with op.batch_alter_table("game_arguments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_game_arguments_game_id"), ["game_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_arguments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_arguments_game_id"))

    op.drop_table("game_arguments")
    op.drop_table("settings")
    op.drop_table("games")
    # ### end Alembic commands ###
