# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:

  build_develop:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Python Black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "."
        version: "~= 22.0"

    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        exclude: "tests/*,doc/*,scripts/*"
        max-line-length: "100"

  build_develop_windows_exe:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Run PyInstaller
      run: |
        python package.py

    - name: Run PyInstaller
      run: |
        python checksum.txt

    - name: Upload Exe Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: AgentSmith-develop
        path: .\dist\agent-smith.exe
        retention-days: 1

    - name: Upload Checksum Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: AgentSmith-develop-checksum.txt
        path: checksum.txt
        retention-days: 1